### PR TITLE
Update chart rather than redrawing it in Shiny

### PR DESCRIPTION
**Pull request by AdeelK93**
Check out your `shiny-examples/options` demo to see what I mean

### CODE REVIEW

**Comment by dougmet** [comment]
This is great!

Do you want to add yourself as a contributor? If so just update the DESCRIPTION file with `role="ctb"` and I'll merge straight in.

**Comment by AdeelK93** [comment]
Sure thing, thank you!

**Comment by dougmet** [comment]
Thanks again, really like this feature.

**Comment by Chrisss93** [comment]
Unfortunately, this appears to prevent the radarchart labels from being dynamically redrawn.

Contrast the behaviour of the following example between v0.3.1 and v0.3.1.9
```
shinyApp(
    pageWithSidebar(
        headerPanel('Radarchart with reactive data'),
        sidebarPanel(
            checkboxGroupInput('eye', 'Eye-color?', attr(HairEyeColor, "dimnames")$Eye, 
                               selected = "Black"),
            checkboxGroupInput("hair", "Hair colors", attr(HairEyeColor, "dimnames")$Hair, 
                               selected = "Black"),
            actionButton("go", "GO!")
        ),
        mainPanel(
            chartJSRadarOutput("radar", width = "450", height = "300"), width = 7
        )
    ),
    function(input, output) {
        obs <- eventReactive(input$go, {
            df <- as.data.frame(HairEyeColor) 
            df <- df[df$Eye %in% input$eye & df$Sex %in% "Male",]
        })
        output$radar <- renderChartJSRadar({
            dta <- tidyr::spread(obs(), Hair, Freq)
            chartJSRadar( dta[, c("Eye", input$hair)] )
        })
    }
)
```

**Comment by AdeelK93** [comment]
Hi @Chrisss93, I've fixed this in #45! Good catch, dynamically updating labels was not something I had tried or considered

**Pull request merged**
