### PR TITLE
remove excess and update to ChartJS `2.1.6`

### PR DESCRIPTION
**Pull request by timelyportfolio**
This pull is a start toward an upgrade to ChartJS [`2.1.6`](https://github.com/chartjs/Chart.js/releases/tag/v2.1.6).  While upgrading, I also cleaned out much of the unnecessary bower remnants.  These remnants get copied, so can slow rendering of the `htmlwidget`.  I also had to make a minor change to `initialize`/`renderValue` to work with the new API.

If you have no interest in upgrading, then please feel free to ignore and close.

### CODE REVIEW

**Comment by timelyportfolio** [comment]
It seems other args have changed also.  I'll try to translate old -> new.

**Comment by dougmet** [comment]
Hi, thanks for the PR! I've also been looking at the Chart.js version 2 quite a bit. I've got most of the version 2 api working in the [feature-v1api](https://github.com/MangoTheCat/radarchart/tree/feature-v1api) branch (the v1 here actually refers to radarchart v1). It seemed like a major version bump in Chart.js probably warranted a review of the api for radarchart as well.

I'm very interested in the cleaning of bower remnants, I hadn't realised that was a performance drag. I'd definitely like to try that out.

Let me think about how best to merge in what you've done with the progress I've made. It would be good to compare to the other branch rather than master.

**Comment by timelyportfolio** [comment]
Great to know.  Should have checked branches.  I will try to rebase and pull to other branch.  My changes are very minimal so don't expect a lot of trouble.

**Comment by timelyportfolio** [comment]
close in favor of #30

**Pull request closed without merging**
